### ISSUE TITLE
MVPレビュー依頼提出

### ISSUE THREAD

**Issue by itsuki9029** [itsuki9029/HabitTracker#21]
## 各種情報
サービスの概要とMVPで検証する事柄：SNSのようにユーザーと繋がり励まし合いながら習慣化を目指すアプリで、必要最低限の機能が実装できているか
サービス名：ハビトラ ~Habit Tracker~
サービスURL： https://habit-tracker-zt83.onrender.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー登録
- [x] プロフィール詳細
- [x] プロフィール編集
- [x] ログイン
- [x] ログアウト
- [x] 習慣一覧
- [x] 習慣作成
- [x] 習慣詳細
- [x] 習慣編集
- [x] フォロー機能
- [x] フォロワー一覧
- [x] フォロー一覧
- [x] ユーザー検索機能
- [x] チェックボックス
- [x] チェックボックスの毎日リセット機能
- [ ] 通知設定
- [x] コメント

## READMEレビュー時から変更した機能
- [x] コメント編集
- [x] コメント削除

## サービスイメージがわかるようなスクリーンショット等
トップページ
![Image](https://github.com/user-attachments/assets/24913e20-cfbd-49bd-b07b-5bbd9ce1aee2)

プロフィール画面
![Image](https://github.com/user-attachments/assets/691acf13-3838-4e11-acf2-eb890f50b6ac)

習慣詳細
![Image](https://github.com/user-attachments/assets/eb19076d-5b0e-45b2-aad6-02dd2c4045cd)

習慣作成
![Image](https://github.com/user-attachments/assets/e41b4db4-e1f3-48e9-872c-3b4a66776e85)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
